services:
  - type: web
    name: itl411-weather-backend
    runtime: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn weatherbackend.wsgi:application"
